[package]
name = "preview_bot"
version = "0.1.0"
license = "MPL-2.0"
edition = "2021"

# runs on aarch64-unknown-linux-gnu

[dependencies]
axum = "0.7.4"
base64 = "0.21.7"
blake3 = "1.5.0"
constant_time_eq = "0.3.0"
dotenv = "0.15.0"
httpdate = "1.0.3"
image = "0.24.8"
imageproc = "0.23.0"
once_cell = "1.19.0"
redis = { version = "0.24.0", features = ["tokio-comp", "connection-manager"] }
regex = "1.10.3"
reqwest = { version = "0.11.24", default-features = false, features = [
    "json",
    "rustls-tls",
    "gzip",
    "brotli",
    "deflate",
] }
rusttype = "0.9.3"
serde = "1.0.196"
serde_json = "1.0.113"
percent-encoding = "2.3.1"
# Specific commit in "next" branch to avoid breaking changes.
serenity = { git = "https://github.com/serenity-rs/serenity", rev="62196ea6c2e6ddc05da737e60b95d61d589700b4", default-features = false, features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "model",
    "utils",
    "rustls_backend",
] }
tokio = { version = "1.36.0", features = ["full"] }
tower-http = { version = "0.5.1", features = ["cors"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = "line-tables-only"
