[package]
name = "preview_bot"
version = "0.1.0"
edition = "2021"

# runs on aarch64-unknown-linux-gnu

[dependencies]
axum = "0.6.20"
base64 = "0.21.4"
blake3 = "1.5.0"
constant_time_eq = "0.3.0"
dotenv = "0.15.0"
httpdate = "1.0.3"
image = "0.24.7"
imageproc = "0.23.0"
once_cell = "1.18.0"
redis = { version = "0.23.3", features = ["tokio-comp", "connection-manager"] }
regex = "1.10.0"
reqwest = { version = "0.11.22", default-features = false, features = [
    "json",
    "rustls-tls",
    "gzip",
    "brotli",
    "deflate",
] }
rusttype = "0.9.3"
serde = "1.0.188"
serde_json = "1.0.107"
serenity = { git = "https://github.com/Kneemund/serenity", branch = "next", default-features = false, features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "model",
    "utils",
    "rustls_backend",
] }
tokio = { version = "1.21.2", features = ["full"] }
tower-http = { version = "0.4.4", features = ["cors"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = "line-tables-only"