[package]
name = "preview_bot"
version = "0.1.0"
license = "MPL-2.0"
edition = "2021"

[dependencies]
axum = { git = "https://github.com/tokio-rs/axum", rev = "refs/pull/2479/head" }
base64 = "0.22.1"
blake3 = "1.5.1"
constant_time_eq = "0.3.0"
httpdate = "1.0.3"
ab_glyph = "0.2.25"
image = "0.25.1"
imageproc = "0.24.0"
once_cell = "1.19.0"
redis = { version = "0.25.3", features = ["tokio-comp", "connection-manager"] }
regex = "1.10.4"
reqwest = { version = "0.12.4", default-features = false, features = [
    "json",
    "rustls-tls",
    "gzip",
    "brotli",
    "deflate",
] }
serde = "1.0.201"
serde_json = "1.0.117"
percent-encoding = "2.3.1"
# Specific commit in "next" branch to avoid breaking changes.
serenity = { git = "https://github.com/serenity-rs/serenity", rev = "3a6c2de93f45c3ef6dcaba026aa32daab04173d9", default-features = false, features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "model",
    "utils",
    "rustls_backend",
] }
tokio = { version = "1.37.0", features = ["full"] }
tower-http = { version = "0.5.2", features = ["cors"] }
dotenvy = "0.15.7"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = "line-tables-only"
