on:
  push:
    branches:
      - master
  workflow_dispatch:

name: Build & Push Images to GHCR

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

concurrency:
  cancel-in-progress: true
  group: publish-ghcr

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REGISTRY }}/${{ github.repository }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          containerfiles: ./Containerfile
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
